MRCIEU/TwoSampleMR

.github/workflows/check-full.yaml, README.md
This is the GitHub Action I mentioned that have been using for `R CMD check`, i.e. as an alternative or in addition to Travis CI.
It is a copy with some minor changes of this by r-lib/actions [here](https://github.com/r-lib/actions/blob/master/examples/check-full.yaml). 
My changes are: 
- I commented out a check on R's oldrelease because you require at least R 3.6.0 - you probably want to maintain a compliance with the oldrelease if you can. Could you re-allow R 3.5.3?
- I changed the operating systems. I think it's faster to use Windows (although some packages still have to be built from source for R devel - and therefore the first run of that takes approx 30 mins) and macOS because R will be able to install compiled versions of the dependency packages. You/I can add some Ubuntu ones if …
=> Add GitHub Actions R-cmd-check

.github/workflows/check-full.yaml, .travis.yml
Given that R-release is now at R 4.0.0 it seems worth running the checks on R 3.6 (one of whose patch versions will now be oldrel) as well as release and devel.
=> Add R 3.6 back into Travis and GitHub Actions checks

R/multivariable_mr.R, README.md
Should be pval.outcome instead of pval.exposure.
l_full[[i]] column becomes pval.exposure after convert_outcome_to_exposure function but the subset happens before this.
=> Fixed bug in mv_extract_exposures_local

R/harmonise.R
When there are multiple variants present for a single SNP, the harmonise function had a small bug where it would duplicate them and attach information related to the other variant. (E.g. SNP rs11177669 using outcome "ukb-b-2227" and exposure "ieu-a-89"). This fix attempts to solve this by creating a new ID for each SNP based on how many variants there are in the dataset. The new ID is removed once the harmonisation is complete.
=> Fix harmonise() for triallelic SNPs

.github/workflows/check-full.yaml, DESCRIPTION, NEWS.md
* Adds Cairo to Imports list (closes #290)
* Tweaks GitHub Actions R-CMD-check workflow to remove the warning about the missing built vignettes
=> Add Cairo package to Imports

.github/workflows/check-full.yaml
* Switch jobs from `ubuntu-16.04` to `ubuntu-18.04` as `ubuntu-16.04` will soon no longer work as per the announcement [here](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/)
* Additional edits following r-lib/actions/examples/check-full.yaml [here](https://github.com/r-lib/actions/blob/630f4c9d8b813f45d0327a2fc20eb264fd518450/examples/check-full.yaml)
=> R-CMD-check GitHub action: move jobs from Ubuntu 16.04 to 18.04 and other edits

.Rbuildignore, .github/workflows/check-full.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml
This fixes the GitHub Actions workflows 
* the R CMD check workflow failed this morning due to r-lib/actions changes - which I've incorporated here (I should have changed from the `@master` syntax sometime ago).
In the R CMD check action I've had to keep the messy code to install the dependencies because MR-PRESSO still fails to install under the **pak** package.
=> Fix GitHub action workflows

NEWS.md, vignettes/gwas2020.Rmd, vignettes/harmonise.Rmd, vignettes/introduction.Rmd, vignettes/perform_mr.Rmd, vignettes/refs.bib
This,
* adds alt text to the images and figures in the vignettes, and hence to the pkgdown site
* various other fixes to typos and other formatting I spotted whilst adding the alt text
=> Add alt text descriptions to images and figures in vignettes

.github/workflows/check-full.yaml, .github/workflows/pkgdown.yaml, CITATION.cff, DESCRIPTION, NEWS.md
This bumps the version number and associated date and 
* bumps the JamesIves GHA workflow to use v4 sliding tag
* amends the CRON job to run `R CMD check` very early on a Tuesday morning
=> Release 0.5.7

.github/workflows/check-full.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, NEWS.md, R/instruments.R, R/multivariable_mr.R, R/query.R, R/zzz.R, inst/sandpit/multivariable_mr.R, inst/sandpit/multivariable_mr.rmd, man/available_outcomes.Rd, man/extract_instruments.Rd, man/extract_outcome_data.Rd, man/mv_extract_exposures.Rd, tests/testthat/test_mvmr_local.R, vignettes/introduction.Rmd
This PR updates the package to use ieugwasr 1.0.0, which moves away from google oauth2 and now uses OpenGWAS jwt for authentication / authorisation. ieugwasr 1.0.0 has been submitted to CRAN.
It's a breaking change as previously anonymous usage was possible, and private dataset access was enabled through google authentication. Also, we're no longer using the GoogleAuthR package which might be removed from CRAN - https://cran.r-project.org/web/checks/check_results_googleAuthR.html.
=> removing google oauth2 authentication and replacing with opengwas jwt

.github/workflows/check-full.yaml, DESCRIPTION, NEWS.md, R/other_formats.R
This moves MendelianRandomization from Imports to Suggests.
This is because one of its dependencies, the [Matrix package](https://cran.r-project.org/package=Matrix), now requires R >= 4.4.0. Moving MendelianRandomization to Suggests means we don't need to make the same requirement in TwoSampleMR.
There are also some tweaks to the GHA runners (adding Intel macOS, and going back another oldrel version due to the recent release of R 4.4.0).
=> TwoSampleMR 0.6.1

DESCRIPTION, NEWS.md, R/format_mr_results2.R, R/heterogeneity.R, R/mr.R, R/query.R, R/read_data.R, tests/testthat/test_format_data.R
* `format_data()` now errors if it detects its `dat` object is of class `'data.table'` and issues a message informing the user to make their dat object simply a `'data.frame'` (thanks to Si Fang @sifang1678)
=> TwoSampleMR 0.6.2

_pkgdown.yml
This enables the new light switch feature in the recently release **pkgdown** 2.1.0.
=> Add dark mode to pkgdown site

R/format_mr_results2.R
This ensures that iv.se will be a scalar not a vector even when the outcome.samplesize varies within outcome subsets.
The current behavior assumes that the samplesize is the same within each outcome subset, and that unique will therefore return a scalar. When this assumption is violated, it returns a vector of samplesize values that is likely to differ in length from the total size of the subset and will therefore produce a size mismatch when assigning it as a column in that data.frame. 
Removing the unique() call and allowing iv.se to be a vector of the size of the outcome subset will not produce an error but it will cause the outcome subsets to be selected according to the largest samplesize among any of the IV SNPs in that subset, which is not the desired behavior.
Using the mean() of …
=> Replaced some unique() calls in power_prune() with mean()

vignettes/perform_mr.Rmd
By not evaluating two chunks, the second of which prevents the MendelianRandomization package from loading (as one of its dependencies requires R >= 4.4.0).
=> Keep the perform_mr vignette building on R 4.3.3 and 4.3.2 

vignettes/perform_mr.Rmd
Run chunks with MendelianRandomization package calls as long as R version >= 4.4.0.
=> Better fix for perform_mr vignette

.github/workflows/check-full.yaml, TwoSampleMR.Rproj
I have building the docker image as multi-platform for a while (i.e., both x96_64 and ARM), so I know that TwoSampleMR builds on Linux on ARM.
https://github.com/MRCIEU/docker_twosamplemr
And GitHub now has Ubuntu on ARM on the free plan: 
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> Add check on Ubuntu Linux 24.04 on ARM

DESCRIPTION, NEWS.md, R/forest_plot2.R, R/instruments.R, R/other_formats.R, R/read_data.R, README.md, index.md, inst/CITATION, man/TwoSampleMR-package.Rd, man/dat_to_MRInput.Rd, man/extract_instruments.Rd, man/format_mr_results.Rd, vignettes/exposure.Rmd
* Fixed a bug in `format_data()` when the `log_pval` argument was set to `TRUE`.
The specified p-value column is now used (thanks to @luddeluddis)
* Amend references to MR-Base to OpenGWAS
Closes #586
=> TwoSampleMR 0.6.9

DESCRIPTION, NEWS.md, tests/testthat/test_mr.R
* The tests using **mr.raps** are now run conditionally.
* The **rsnps** package has been removed from Suggests because the configuration of **mr.raps** has been corrected.
=> TwoSampleMR v0.6.11

DESCRIPTION, NEWS.md, R/mr.R, R/multivariable_mr.R, R/read_data.R, codecov.yml, vignettes/perform_mr.Rmd, vignettes/refs.bib
* Fixed a bug in `format_data()` (thanks to @lea-urpa)
* For MVMR data extraction in `mv_extract_exposures()` and `mv_extract_exposures_local()`, SNPs that do not pass harmonisation between exposures in MVMR are now dropped (thanks @yatest)
* The comments about **mr.raps** in the Perform MR vignette have been updated
Closes #45 
Closes #592
=> TwoSampleMR v0.6.12

.github/workflows/check-full.yaml
Due to release of R 4.5.0, R 4.3.3 is now oldrel-2.
=> Check on oldrel-2

.github/workflows/check-full.yaml
It turns out `macos-latest` is still on macOS 14.
=> Add check on macos-15

.github/workflows/check-full.yaml, DESCRIPTION, NEWS.md, inst/sandpit/test_mr_sign.R
* Bumped the minimum required version of R to 4.1.0. This is due to a dependency (the scales package) of a dependency (the ggplot2 package), which now has this requirement.
=> TwoSampleMR v0.6.15
